# -*- coding: utf-8 -*-
"""evaluator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6KsRIWsXcMe0hHmtAyKgC1wUDWx4Pb_
"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from typing import List

def evaluate_model(model, X_test, y_test, label_encoder):

    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    print("Accuracy:", round(acc * 100, 2), "%\n")

    print("Classification Report:")
    print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))


def predict_intent(text: str, vectorizer, model, label_encoder):

    X = vectorizer.transform([text])
    pred = model.predict(X)[0]
    return label_encoder.inverse_transform([pred])[0]

