# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rSNGsAA25ELqmxkIHlj-SFISogJdvml0
"""

# we will export every python script
# from dataset_loading import load_data_from_kagglehub
from dataset_loading import load_data_from_local

texts, labels, intents_data = load_data_from_local()

from vectorizer import train_vectorizer, save_vectorizer
from model import encode_labels, train_svm, save_model
from evaluator import evaluate_model, predict_intent

def main():
    # print("Loading dataset::::::")
    # texts, labels, intents_data = load_data_from_kagglehub()

    print("Loading dataset::::::")
    texts, labels, intents_data = load_data_from_local()


    print("Vectorizing texts::::")
    vectorizer, X = train_vectorizer(texts)
    save_vectorizer(vectorizer)

    print("Encoding labels:::")
    y, label_encoder = encode_labels(labels)

    print("Training SVM classifier::::")
    model = train_svm(X, y)
    save_model(model)

    print("Evaluating model:::")
    evaluate_model(model, X, y, label_encoder)

    test_input = "How are you boiiii?"
    predicted = predict_intent(test_input, vectorizer, model, label_encoder)
    print(f"\nTest Input: {test_input}\nPredicted Intent: {predicted}")


if __name__ == "__main__":
    main()