# -*- coding: utf-8 -*-
"""model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQiIRxKTdKuZmp_tXNv_-TuZkc5Mdpf1
"""

from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder
import pickle
from typing import List, Tuple

def encode_labels(labels: List[str]) -> Tuple[List[int], LabelEncoder]:

    le = LabelEncoder()
    encoded_labels = le.fit_transform(labels)
    return encoded_labels, le


def train_svm(X, y) -> SVC:

    model = SVC(kernel='linear', probability=True)
    model.fit(X, y)
    return model


def save_model(model, path: str = "svm_model.pkl") -> None:

    with open(path, "wb") as f:
        pickle.dump(model, f)


def load_model(path: str = "svm_model.pkl"):

    with open(path, "rb") as f:
        return pickle.load(f)

